name: Build and Test on Push

on:
  push:
    branches: [ master, develop, qa, release ]

jobs:
  BUILD_VALIDATE_JOB_ON_PUSH:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        source-url: ${{ env.NUGET_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.IKOMM_READ_PACKAGES_TOKEN }}
        NUGET_URL: https://nuget.pkg.github.com/IkommAS/index.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
